export const CI_STATUS = {
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  ERROR: "ERROR",
  PENDING: "PENDING",
} as const;

export const REVIEW_DECISION = {
  APPROVED: "APPROVED",
  CHANGES_REQUESTED: "CHANGES_REQUESTED",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
} as const;

export const MERGEABLE_STATE = {
  MERGEABLE: "MERGEABLE",
  CONFLICTING: "CONFLICTING",
  UNKNOWN: "UNKNOWN",
} as const;
